# Generated by Django 5.2 on 2025-04-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('img', models.TextField()),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
