# Generated by Django 5.2 on 2025-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
            ],
        ),
    ]
